In [1]:
import pandas as pd

In [3]:
population = pd.read_csv('data/population.csv')
population

,Rank,State,Capital,Population,% of Total Population,Males,Females,Sex Ratio,Literacy Rate (%),Rural Population,Urban Population,Area (km*km),Density (1/km*km),Decadal Growth (%)
0,1,Uttar Pradesh,Lucknow,"199,812,341",16.50,"104,480,510","95,331,831",912,67.68,"155,111,022","44,470,455","240,928",828,20.1%
1,2,Maharashtra,Mumbai,"112,374,333",9.28,"58,243,056","54,131,277",929,82.34,"61,545,441","50,827,531","307,713",365,16.0%
2,3,Bihar,Patna,"104,099,452",8.60,"54,278,157","49,821,295",918,61.80,"92,075,028","11,729,609","94,163","1,102",25.1%
3,4,West Bengal,Kolkata,"91,276,115",7.54,"46,809,027","44,467,088",950,76.26,"62,213,676","29,134,060","88,752","1,030",13.9%
4,5,Andhra Pradesh,Hyderabad,"84,580,777",6.99,"42,442,146","42,138,631",993,67.02,"56,361,702","28,219,075","275,045",308,10.98%
5,6,Madhya Pradesh,Bhopal,"72,626,809",6.00,"37,612,306","35,014,503",931,69.32,"52,537,899","20,059,666","308,245",236,20.3%
6,7,Tamil Nadu,Chennai,"72,147,030",5.96,"36,137,975","36,009,055",996,80.09,"37,189,229","34,949,729","130,058",555,15.6%
7,8,Rajasthan,Jaipur,"68,548,437",5.66,"35,550,997","32,997,440",928,66.11,"51,540,236","17,080,776","342,239",201,21.4%
8,9,Karnataka,Bengaluru,"61,095,297",5.05,"30,966,657","30,128,640",973,75.36,"37,552,529","23,578,175","191,791",319,15.7%
9,10,Gujarat,Gandhinagar,"60,439,692",4.99,"31,491,260","28,948,432",919,78.03,"34,670,817","25,712,811","196,024",308,19.2%
10,11,Odisha,Bhubaneshwar,"41,974,218",3.47,"21,212,136","20,762,082",979,72.87,"34,951,234","6,996,124","155,707",269,14.0%
11,12,Kerala,Thiruvananthapuram,"33,406,061",2.76,"16,027,412","17,378,649","1,084",94.00,"17,445,506","15,932,171","38,863",859,4.9%
12,13,Jharkhand,Ranchi,"32,988,134",2.72,"16,930,315","16,057,819",948,66.41,"25,036,946","7,929,292","79,714",414,22.3%
13,14,Assam,Dispur,"31,205,576",2.58,"15,939,443","15,266,133",958,72.19,"26,780,526","4,388,756","78,438",397,16.9%
14,15,Punjab,Chandigarh,"27,743,338",2.29,"14,639,465","13,103,873",895,75.84,"17,316,800","10,387,436","50,362",550,13.7%
15,16,Chhattisgarh,Raipur,"25,545,198",2.11,"12,832,895","12,712,303",991,70.28,"19,603,658","5,936,538","135,191",189,22.6%
16,17,Haryana,Chandigarh,"25,351,462",2.09,"13,494,734","11,856,728",879,75.55,"16,531,493","8,821,588","44,212",573,19.9%
17,18,Delhi,Delhi,"16,787,941",1.39,"8,887,326","7,800,615",868,86.21,"944,727","12,905,780","1,484","11,297",21%
18,19,Jammu and Kashmir,NaN,"12,541,302",1.04,"6,640,662","5,900,640",889,67.16,"9,134,820","3,414,106","222,236",56,23.7%
19,20,Uttarakhand,Dehradun,"10,086,292",0.83,"5,137,773","4,948,519",963,79.63,"7,025,583","3,091,169","53,483",189,19.2%
20,21,Himachal Pradesh,Shimla,"6,864,602",0.57,"3,481,873","3,382,729",972,82.80,"6,167,805","688,704","55,673",123,12.8%
21,22,Tripura,Agartala,"3,673,917",0.30,"1,874,376","1,799,541",960,87.22,"2,710,051","960,981","10,486",350,14.7%
22,23,Meghalaya,Shillong,"2,966,889",0.25,"1,491,832","1,475,057",989,74.43,"2,368,971","595,036","22,429",132,27.8%
23,24,Manipur,Imphal,"2,721,756",0.21,"1,290,171","1,280,219",992,79.21,"1,899,624","822,132","22,327",122,18.7%
24,25,Nagaland,Kohima,"1,978,502",0.16,"1,024,649","953,853",931,79.55,"1,406,861","573,741","16,579",119,−0.5%
25,26,Goa,Panaji,"1,458,545",0.12,"739,140","719,405",973,88.70,"551,414","906,309","3,702",394,8.2%
26,27,Arunachal Pradesh,Itanagar,"1,383,727",0.11,"713,912","669,815",938,65.38,"1,069,165","313,446","83,743",17,25.9%
27,28,Puducherry,Pondicherry,"1,247,953",0.10,"612,511","635,442","1,037",85.85,"394,341","850,123",479,"2,598",27.7%
28,29,Mizoram,Aizawl,"1,097,206",0.09,"555,339","541,867",976,91.33,"529,037","561,997","21,081",52,22.8%
29,30,Chandigarh,Chandigarh,"1,055,450",0.09,"580,663","474,787",818,86.05,"29,004","1,025,682",114,"9,252",17.1%
30,31,Sikkim,Gangtok,"610,577",0.05,"323,070","287,507",890,81.42,"455,962","151,726","7,096",86,12.4%
31,32,Andaman and Nicobar Islands,Port Blair,"380,581",0.03,"202,871","177,710",876,86.63,"244,411","135,533","8,249",46,6.7%
32,33,Dadra and Nagar Haveli,Silvassa,"343,709",0.03,"193,760","149,949",774,76.24,"183,024","159,829",491,698,55.5%
33,34,Daman and Diu,Daman,"243,247",0.02,"150,301","92,946",618,87.10,"60,331","182,580",112,"2,169",53.5%
34,35,Lakshadweep,Kavaratti,"64,473",0.01,"33,123","31,350",946,91.85,"14,121","50,308",32,"2,013",6.2%

In [5]:
population.shape

(35, 14)

In [7]:
population.isnull().count()

Rank                     35
State                    35
Capital                  35
Population               35
% of Total Population    35
Males                    35
Females                  35
Sex Ratio                35
Literacy Rate (%)        35
Rural Population         35
Urban Population         35
Area (km*km)             35
Density (1/km*km)        35
Decadal Growth (%)       35
dtype: int64

In [9]:
population.dtypes

Rank                       int64
State                     object
Capital                   object
Population                object
% of Total Population    float64
Males                     object
Females                   object
Sex Ratio                 object
Literacy Rate (%)        float64
Rural Population          object
Urban Population          object
Area (km*km)              object
Density (1/km*km)         object
Decadal Growth (%)        object
dtype: object